[project]
name = "kiara-bootstrapper"
version = "0.1.0"
description = "install python and stuff for kiara UIs"
authors = []
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
compile-python = "env PYTHON_CONFIGURE_OPTS=\"--enable-shared\" PYTHON_BUILD_DEFINITIONS=$PWD bash ./python-build 3.11.5 $PWD/python"


[dependencies]
# TODO maybe other things if people don't have xcode?
openssl = "3.*"
cmake = "3.27.9.*"

[target.linux-64.dependencies]
gcc = "13.2.0.*"

[target.osx-64.dependencies]
clang-16 = "*"

[target.osx-arm64.dependencies]
clang-16 = "*"